export const products = [
  [
    'p1',
    'farm',
    '本地鲜摘小番茄',
    '酸甜爆汁，把新鲜带回家',
    690,
    '500g / 盒',
    'tomato',
    '今日鲜摘',
    '邻里鲜蔬',
    0.6,
    128,
  ],
  [
    'p2',
    'farm',
    '奶油生菜',
    '水灵脆嫩，今天多吃一点绿',
    450,
    '约 350g / 份',
    'lettuce',
    '时令推荐',
    '邻里鲜蔬',
    0.6,
    96,
  ],
  [
    'p3',
    'farm',
    '阳光橙子',
    '皮薄多汁，装满一袋阳光',
    1290,
    '4 个 / 份',
    'orange',
    '当季好果',
    '果然新鲜',
    1.2,
    86,
  ],
  [
    'p4',
    'farm',
    '农家鲜鸡蛋',
    '每天的营养，从早餐开始',
    1590,
    '10 枚 / 盒',
    'eggs',
    '早餐优选',
    '田野农场',
    2.1,
    62,
  ],
  [
    'p5',
    'farm',
    '甜糯小玉米',
    '蒸一蒸，就是自然的甜',
    890,
    '2 根 / 份',
    'corn',
    '农场直供',
    '田野农场',
    2.1,
    75,
  ],
  [
    'p6',
    'farm',
    '脆甜胡萝卜',
    '清甜好滋味，炖煮都合适',
    390,
    '500g / 份',
    'carrot',
    '实惠好菜',
    '邻里鲜蔬',
    0.6,
    93,
  ],
  [
    'p7',
    'clothes',
    '日常纯棉 T 恤',
    '柔软透气，穿得自在',
    5900,
    '件',
    'shirt',
    '舒适纯棉',
    '巷口衣橱',
    0.8,
    38,
  ],
  [
    'p8',
    'clothes',
    '轻风帆布托特包',
    '装下日常，也装下好心情',
    3900,
    '只',
    'bag',
    '通勤百搭',
    '巷口衣橱',
    0.8,
    42,
  ],
  [
    'p9',
    'clothes',
    '松弛感衬衫',
    '干净的颜色，轻盈的日常',
    8900,
    '件',
    'blouse',
    '新品上架',
    '街角女装',
    1.5,
    23,
  ],
  [
    'p10',
    'clothes',
    '经典休闲运动鞋',
    '轻巧好走，出门逛逛',
    12900,
    '双',
    'shoe',
    '同城好店',
    '步履鞋坊',
    1.8,
    25,
  ],
  [
    'p11',
    'clothes',
    '简约针织开衫',
    '换季时，刚刚好的温暖',
    11900,
    '件',
    'cardigan',
    '秋日精选',
    '街角女装',
    1.5,
    20,
  ],
  [
    'p12',
    'clothes',
    '轻便棒球帽',
    '给日常添一点颜色',
    2900,
    '顶',
    'cap',
    '出游必备',
    '巷口衣橱',
    0.8,
    45,
  ],
].map(([id, category, title, subtitle, price, unit, art, tag, shop, distance, stock]) => ({
  id,
  category,
  title,
  subtitle,
  price,
  unit,
  art,
  tag,
  shop,
  distance,
  stock,
  options:
    category === 'clothes'
      ? art === 'shoe'
        ? ['37', '38', '39', '40', '41', '42']
        : ['shirt', 'blouse', 'cardigan'].includes(art)
          ? ['S', 'M', 'L', 'XL']
          : ['均码']
      : ['标准'],
  description:
    category === 'farm'
      ? '本地门店精选食材。图片为商品示意，实际规格以门店确认的信息为准。演示订单不收取费用，也不会安排真实配送。'
      : '来自附近的日常衣橱。图片为款式示意，下单前请确认规格。演示订单不收取费用，也不会安排真实配送。',
}));
export const services = [
  {
    id: 's1',
    title: '空调清洗',
    subtitle: '清洗滤网 · 蒸发器除尘',
    art: 'aircon',
    price: 8900,
    unit: '台起',
    duration: '约 60 分钟',
    rating: '4.9',
    jobs: 268,
    tag: '热门服务',
    description: '基础报价包含一台挂机清洗。高空作业、柜机和额外耗材需在服务前确认报价。',
  },
  {
    id: 's2',
    title: '水电维修',
    subtitle: '漏水处理 · 电路检修',
    art: 'repair',
    price: 3900,
    unit: '次起',
    duration: '约 30–90 分钟',
    rating: '4.8',
    jobs: 186,
    tag: '邻里常用',
    description: '39 元为上门检查参考价。零件与维修费用需由师傅检查后报价，经你确认再施工。',
  },
  {
    id: 's3',
    title: '家电检修',
    subtitle: '洗衣机 · 冰箱 · 热水器',
    art: 'washer',
    price: 4900,
    unit: '次起',
    duration: '约 60 分钟',
    rating: '4.9',
    jobs: 152,
    tag: '专业检修',
    description: '49 元为检查参考价。维修和零件费用另行确认，无法维修时按实际约定结算。',
  },
  {
    id: 's4',
    title: '居家保洁',
    subtitle: '日常清洁 · 厨卫焕新',
    art: 'clean',
    price: 9900,
    unit: '2 小时起',
    duration: '约 120 分钟',
    rating: '4.9',
    jobs: 326,
    tag: '省心到家',
    description: '基础服务包含两小时日常清洁，不含外窗、高空作业与深度开荒。',
  },
];
export const listings = [
  {
    id: 'm1',
    title: '搬家出一个原木小边桌',
    description: '放在床边刚刚好，使用半年，无明显磕碰。同城自提，具体状态请当面确认。',
    price: 6500,
    art: 'table',
    condition: '九成新',
    area: '西湖区',
    city: '杭州',
    nickname: '小周的日常',
    distance: 0.8,
  },
  {
    id: 'm2',
    title: '复古城市通勤自行车',
    description: '平时周末骑，刹车和车铃正常，适合通勤。演示物品，仅供体验浏览。',
    price: 28000,
    art: 'bike',
    condition: '八成新',
    area: '拱墅区',
    city: '杭州',
    nickname: '骑车去买花',
    distance: 1.6,
  },
  {
    id: 'm3',
    title: '闲置迷你咖啡机',
    description: '外观干净，配件齐全，送量勺。同城当面验货。演示物品，不实际出售。',
    price: 12000,
    art: 'coffee',
    condition: '九成新',
    area: '上城区',
    city: '杭州',
    nickname: '一杯拿铁',
    distance: 2.3,
  },
  {
    id: 'm4',
    title: '绿植小盆栽，一起带走',
    description: '两盆好养的绿植，为书桌添点绿。演示物品，不实际出售。',
    price: 2000,
    art: 'plant',
    condition: '全新',
    area: '西湖区',
    city: '杭州',
    nickname: '窗边的风',
    distance: 1.1,
  },
];
